#!/usr/bin/env bash
# FOR USE BY install.sh

# Manual installation
REMARKABLE_DEB=$TEMP_DIR/remarkable.deb

#if dpkg --get-selections | grep -q "^remarkable-1.87\s*install$"; then
if is_installed "remarkable-1.87"; then
  echo_found  "Remarkable"
else
  echo_adding "Remarkable"
  if [ ! -f $REMARKABLE_DEB ]; then
    wget -q http://remarkableapp.github.io/files/remarkable_1.87_all.deb -O $REMARKABLE_DEB
  fi

  gdebi -qn $REMARKABLE_DEB
fi
