#!/usr/bin/env bash
# FOR USE BY install.sh

# Manual installation
ONLYOFFICE_DEB=$TEMP_DIR/onlyoffice.deb

if is_installed "onlyoffice-desktopeditors"; then
  echo_found  "OnlyOffice"
else
  echo_adding "OnlyOffice"
  if [ ! -f $ONLYOFFICE_DEB ]; then
    wget -q https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb -O $ONLYOFFICE_DEB
  fi

  gdebi -qn $ONLYOFFICE_DEB
fi
